spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/potion_brewery?useTimezone=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  spring-doc:
    paths-to-match:
      - /api/**/v1/**
      - /auth/**
    swagger-ui:
      use-root-path: true